"""final update

Revision ID: 01ba34b13188
Revises: 48a14c2c3816
Create Date: 2023-07-19 14:52:06.572131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ba34b13188'
down_revision = '48a14c2c3816'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
