"""change model name

Revision ID: a80b62994345
Revises: d17983750cba
Create Date: 2023-07-14 12:49:24.765146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80b62994345'
down_revision = 'd17983750cba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('players', 'last_name')
    op.drop_column('players', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('first_name', sa.VARCHAR(), nullable=True))
    op.add_column('players', sa.Column('last_name', sa.VARCHAR(), nullable=True))
    op.drop_column('players', 'username')
    # ### end Alembic commands ###
