"""updated deck model

Revision ID: bcc69cf82404
Revises: f261c26c684d
Create Date: 2023-07-17 14:41:40.703798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc69cf82404'
down_revision = 'f261c26c684d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
