"""changed deck and card models

Revision ID: d17983750cba
Revises: 8a157d7c1cfd
Create Date: 2023-07-12 10:48:32.215327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17983750cba'
down_revision = '8a157d7c1cfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('card_name', sa.String(), nullable=True))
    op.drop_column('cards', 'name')
    op.add_column('decks', sa.Column('deck_name', sa.String(), nullable=True))
    op.drop_column('decks', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('decks', 'deck_name')
    op.add_column('cards', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('cards', 'card_name')
    # ### end Alembic commands ###
