"""changed card model

Revision ID: f261c26c684d
Revises: a80b62994345
Create Date: 2023-07-17 11:47:54.524833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f261c26c684d'
down_revision = 'a80b62994345'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
